rule = "103.2b"
section = 103
title = "Starting the Game - CR 103.2b"
status = "skeleton"
text = "If any players wish to reveal a card with a companion ability that they own from outside the game, they may do so. A player may reveal no more than one card this way, and they may do so only if their deck fulfills the condition of that card’s companion ability. The revealed card remains outside the game. (See rule 702.139, “Companion.”)"
