//! "becomes the <creature type | basic land type | color> of your choice ...
//! until end of turn" must install its continuous effect for the PRINTED window
//! only (backlog §25, "Wrong / dropped effect duration").
//!
//! CR 611.2a: "A continuous effect generated by the resolution of a spell or
//! ability lasts as long as stated by the spell or ability creating it (such as
//! 'until end of turn')." CR 514.2: in the cleanup step, "until end of turn"
//! effects end. Before the fix, `try_parse_become_choice` built the
//! `Effect::Choose` → `Effect::GenericEffect` apply chain with the apply half's
//! definition duration unset and its embedded duration `Permanent`; the printed
//! trailing window, peeled upstream, was stamped on the `Choose` head only, and
//! `effect::resolve` reads the apply half's own definition before the embedded
//! value. So Mistform Stalker's "until end of turn" installed a PERMANENT effect.
//!
//! REVERT DISCRIMINATORS:
//! * `mistform_stalker_creature_type_choice_ends_at_cleanup` (R1) — the
//!   `installed[0].duration == Duration::UntilEndOfTurn` assertion (BASE:
//!   `Duration::Permanent`), and the post-boundary emptiness assertion.
//! * `jinx_basic_land_type_choice_ends_at_cleanup` (R2) — same two assertions on
//!   the basic-land-type axis.
//!
//! `alchors_tomb_unwindowed_color_choice_stays_permanent` (R3) is the negative
//! sibling: a clause that prints NO window keeps the CR 611.2a `Permanent`
//! default and survives the boundary. It passes at BASE by design.
//!
//! The installed effect is located by its LATCHED payload: the `persist: false`
//! answer is fixed into the modification when the effect is applied (CR 608.2h,
//! `effects/effect.rs::snapshot_transient_modifications`), so Mistform Stalker's
//! effect carries `AddSubtype { "Elf" }` and Jinx's `SetBasicLandType { Island }`.
//! R1/R2 also check the chosen type is visible before cleanup, so the window
//! assertions are about an effect that actually applies; set-versus-retain
//! semantics are covered by `become_chosen_subtype.rs`.
//!
//! Every card is built from VERBATIM Oracle text (`/card-test`).

use engine::game::layers::evaluate_layers;
use engine::game::scenario::{GameRunner, GameScenario, P0, P1};
use engine::types::ability::{BasicLandType, ColorChangeMode, ContinuousModification, Duration};
use engine::types::actions::GameAction;
use engine::types::game_state::{GameState, TransientContinuousEffect, WaitingFor};
use engine::types::identifiers::ObjectId;
use engine::types::mana::{ManaColor, ManaCost, ManaCostShard, ManaType, ManaUnit};
use engine::types::phase::Phase;

/// Mistform Stalker {1}{U} Creature — Illusion 1/1 — verbatim Oracle text.
const MISTFORM_STALKER: &str = "{1}: This creature becomes the creature type of your choice until end of turn.\n{2}{U}{U}: This creature gets +2/+2 and gains flying until end of turn.";

/// Jinx {1}{U} Instant — verbatim Oracle text.
const JINX: &str = "Target land becomes the basic land type of your choice until end of turn.\nDraw a card at the beginning of the next turn's upkeep.";

/// Alchor's Tomb {4} Artifact — verbatim Oracle text.
const ALCHORS_TOMB: &str = "{2}, {T}: Target permanent you control becomes the color of your choice. (This effect lasts indefinitely.)";

fn mana(units: &[(ManaType, usize)]) -> Vec<ManaUnit> {
    let mut pool = Vec::new();
    for &(color, n) in units {
        for _ in 0..n {
            pool.push(ManaUnit::new(color, ObjectId(0), false, vec![]));
        }
    }
    pool
}

/// The live `TransientContinuousEffect`s carrying `modification` — the runtime
/// carrier the apply half's `GenericEffect` becomes.
fn effects_with<'a>(
    state: &'a GameState,
    modification: &ContinuousModification,
) -> Vec<&'a TransientContinuousEffect> {
    state
        .transient_continuous_effects
        .iter()
        .filter(|e| e.modifications.contains(modification))
        .collect()
}

/// CR 613.1: re-derive the object's characteristics from all live continuous
/// effects, then read its subtypes back.
fn subtypes_after_layers(runner: &mut GameRunner, id: ObjectId) -> Vec<String> {
    runner.state_mut().layers_dirty.mark_full();
    evaluate_layers(runner.state_mut());
    runner.state().objects[&id].card_types.subtypes.clone()
}

/// Seed both libraries so the turn walk below never decks a player.
fn seed_libraries(scenario: &mut GameScenario) {
    for i in 0..10 {
        scenario.add_card_to_library_top(P0, &format!("MyLib{i}"));
        scenario.add_card_to_library_top(P1, &format!("OppLib{i}"));
    }
}

/// Advance past the current turn's cleanup step (CR 514.2) into the next turn.
/// Bounded; asserts the boundary was actually crossed, so a stalled walk can
/// never make an expiry assertion pass vacuously.
fn cross_turn_boundary(runner: &mut GameRunner) {
    let start = runner.state().turn_number;
    for _ in 0..400 {
        if runner.state().turn_number > start {
            break;
        }
        let action = match runner.state().waiting_for {
            WaitingFor::DeclareAttackers { .. } => GameAction::DeclareAttackers {
                attacks: vec![],
                bands: vec![],
            },
            WaitingFor::DeclareBlockers { .. } => GameAction::DeclareBlockers {
                assignments: vec![],
            },
            _ => GameAction::PassPriority,
        };
        if runner.act(action).is_err() {
            break;
        }
    }
    // REACH GUARD: without this an expiry assertion passes vacuously on a walk
    // that never left the turn.
    assert!(
        runner.state().turn_number > start,
        "turn boundary was not crossed: still turn {start}, phase {:?}, waiting {:?}",
        runner.state().phase,
        runner.state().waiting_for
    );
    runner.state_mut().layers_dirty.mark_full();
    evaluate_layers(runner.state_mut());
}

/// R1 — CR 611.2a + CR 514.2. Mistform Stalker's printed "until end of turn"
/// reaches the installed creature-type effect, which ends at cleanup.
#[test]
fn mistform_stalker_creature_type_choice_ends_at_cleanup() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);
    scenario.with_mana_pool(P0, mana(&[(ManaType::Colorless, 4)]));
    let stalker = scenario
        .add_creature_from_oracle(P0, "Mistform Stalker", 1, 1, MISTFORM_STALKER)
        .id();
    seed_libraries(&mut scenario);
    let mut runner = scenario.build();

    runner.activate(stalker, 0).choose_option("Elf").resolve();

    // CR 608.2h: the chosen creature type is latched into the payload.
    let creature_type = ContinuousModification::AddSubtype {
        subtype: "Elf".to_string(),
    };
    let installed = effects_with(runner.state(), &creature_type);
    // POSITIVE REACH GUARD: the apply half resolved and installed its effect.
    assert_eq!(
        installed.len(),
        1,
        "the creature-type effect must be installed: {:?}",
        runner.state().transient_continuous_effects
    );
    // THE REVERT-FAILING ASSERTION (BASE: Duration::Permanent).
    assert_eq!(
        installed[0].duration,
        Duration::UntilEndOfTurn,
        "CR 611.2a: the printed `until end of turn` must reach the apply half"
    );
    let before_cleanup = subtypes_after_layers(&mut runner, stalker);
    assert!(
        before_cleanup.iter().any(|t| t == "Elf"),
        "CR 205.1a: the chosen creature type must apply before cleanup: {before_cleanup:?}"
    );

    cross_turn_boundary(&mut runner);
    assert!(
        effects_with(runner.state(), &creature_type).is_empty(),
        "CR 514.2: the effect must end at cleanup: {:?}",
        runner.state().transient_continuous_effects
    );
}

/// R2 — CR 611.2a + CR 514.2. Jinx's printed "until end of turn" reaches the
/// installed basic-land-type effect, which ends at cleanup.
#[test]
fn jinx_basic_land_type_choice_ends_at_cleanup() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);
    scenario.with_mana_pool(P0, mana(&[(ManaType::Blue, 1), (ManaType::Colorless, 1)]));
    let forest = scenario.add_basic_land(P1, ManaColor::Green);
    let jinx = scenario
        .add_spell_to_hand_from_oracle(P0, "Jinx", true, JINX)
        .with_mana_cost(ManaCost::Cost {
            shards: vec![ManaCostShard::Blue],
            generic: 1,
        })
        .id();
    seed_libraries(&mut scenario);
    let mut runner = scenario.build();

    runner
        .cast(jinx)
        .target_object(forest)
        .choose_option("Island")
        .resolve();

    // CR 608.2h: the chosen basic land type is latched into the payload.
    let land_type = ContinuousModification::SetBasicLandType {
        land_type: BasicLandType::Island,
    };
    let installed = effects_with(runner.state(), &land_type);
    // POSITIVE REACH GUARD: the apply half resolved and installed its effect.
    assert_eq!(
        installed.len(),
        1,
        "the basic-land-type effect must be installed: {:?}",
        runner.state().transient_continuous_effects
    );
    // THE REVERT-FAILING ASSERTION (BASE: Duration::Permanent).
    assert_eq!(
        installed[0].duration,
        Duration::UntilEndOfTurn,
        "CR 611.2a: the printed `until end of turn` must reach the apply half"
    );
    let before_cleanup = subtypes_after_layers(&mut runner, forest);
    assert!(
        before_cleanup.iter().any(|t| t == "Island"),
        "CR 305.7: the chosen basic land type must apply before cleanup: {before_cleanup:?}"
    );

    cross_turn_boundary(&mut runner);
    assert!(
        effects_with(runner.state(), &land_type).is_empty(),
        "CR 514.2: the effect must end at cleanup: {:?}",
        runner.state().transient_continuous_effects
    );
}

/// R3 — CR 611.2a negative sibling. Alchor's Tomb prints no window, so its
/// colour effect keeps the `Permanent` default and survives the boundary. Passes
/// at BASE by design; it pins that the fix does not invent a window.
#[test]
fn alchors_tomb_unwindowed_color_choice_stays_permanent() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);
    scenario.with_mana_pool(P0, mana(&[(ManaType::Colorless, 4)]));
    let tomb = scenario
        .add_artifact_from_oracle(P0, "Alchor's Tomb", ALCHORS_TOMB)
        .id();
    let bear = scenario.add_creature(P0, "Grizzly Bears", 2, 2).id();
    seed_libraries(&mut scenario);
    let mut runner = scenario.build();

    runner
        .activate(tomb, 0)
        .target_object(bear)
        .choose_option("Blue")
        .resolve();

    let set_color = ContinuousModification::AddChosenColor {
        mode: ColorChangeMode::Set,
    };
    let installed = effects_with(runner.state(), &set_color);
    // POSITIVE REACH GUARD: the apply half resolved and installed its effect.
    assert_eq!(
        installed.len(),
        1,
        "the colour effect must be installed: {:?}",
        runner.state().transient_continuous_effects
    );
    assert_eq!(
        installed[0].duration,
        Duration::Permanent,
        "CR 611.2a: a clause with no stated duration lasts until the end of the game"
    );

    cross_turn_boundary(&mut runner);
    assert_eq!(
        effects_with(runner.state(), &set_color).len(),
        1,
        "a permanent effect must survive cleanup: {:?}",
        runner.state().transient_continuous_effects
    );
}
