//! Phantom General — "Creature tokens you control get +1/+1."
//!
//! Regression coverage for the continuous static P/T anthem building block on
//! the **token** filter axis, exercised across every dimension the Oracle
//! clause carries:
//!   - **token-ness** — only token creatures are buffed (CR 111.1 tokens),
//!   - **creature** — the filter is creature-typed (CR 205.2 card types),
//!   - **"you control"** — opponents' tokens are excluded (CR 109.5).
//!
//! The buff is a Layer 7c power/toughness modification generated by a static
//! ability (CR 613.4c), recomputed every layer pass (CR 611.3). This drives the
//! REAL parse → synthesis → layer pipeline (`add_creature_from_oracle` runs the
//! same `synthesize_all` path as production) and reads back the EFFECTIVE
//! post-`evaluate_layers` power/toughness — it is a runtime test, not an
//! AST-shape test.

use engine::game::layers::evaluate_layers;
use engine::game::scenario::{GameRunner, GameScenario, P0, P1};
use engine::types::ability::ContinuousModification;
use engine::types::identifiers::ObjectId;
use engine::types::phase::Phase;

const PHANTOM_GENERAL: &str = "Creature tokens you control get +1/+1.";

/// Recompute layers and read an object's effective (post-layer) power/toughness.
fn effective_pt(runner: &mut GameRunner, id: ObjectId) -> (i32, i32) {
    runner.state_mut().layers_dirty.mark_full();
    evaluate_layers(runner.state_mut());
    let obj = &runner.state().objects[&id];
    (
        obj.power.expect("creature has power"),
        obj.toughness.expect("creature has toughness"),
    )
}

/// Flag an existing battlefield object as a token (CR 111.1).
fn mark_token(runner: &mut GameRunner, id: ObjectId) {
    runner
        .state_mut()
        .objects
        .get_mut(&id)
        .expect("object exists")
        .is_token = true;
}

/// Structural sanity: the parsed Oracle clause must carry a single continuous
/// static granting +1/+1. This is a light guard; the discriminating evidence is
/// the runtime layer behavior below.
#[test]
fn phantom_general_parses_token_anthem_static() {
    let mut scenario = GameScenario::new();
    let general = scenario
        .add_creature_from_oracle(P0, "Phantom General", 2, 2, PHANTOM_GENERAL)
        .id();
    let runner = scenario.build();
    let statics = runner.state().objects[&general]
        .static_definitions
        .as_slice();
    assert!(
        statics.iter().any(|sd| {
            sd.modifications
                .iter()
                .any(|m| matches!(m, ContinuousModification::AddPower { value: 1 }))
                && sd
                    .modifications
                    .iter()
                    .any(|m| matches!(m, ContinuousModification::AddToughness { value: 1 }))
        }),
        "Phantom General must carry a +1/+1 anthem static, statics={statics:?}"
    );
}

#[test]
fn phantom_general_buffs_only_tokens_you_control() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);

    // Source: a 2/2 non-token carrying the anthem (built through the real parse
    // + synthesis pipeline).
    let general = scenario
        .add_creature_from_oracle(P0, "Phantom General", 2, 2, PHANTOM_GENERAL)
        .id();

    // A token creature you control — the +1/+1 subject.
    let your_token = scenario.add_creature(P0, "Soldier Token", 1, 1).id();

    // A non-token creature you control — outside the token filter.
    let your_nontoken = scenario.add_creature(P0, "Grizzly Bears", 2, 2).id();

    // An opponent's token — outside the "you control" filter.
    let foe_token = scenario.add_creature(P1, "Goblin Token", 1, 1).id();

    let mut runner = scenario.build();
    mark_token(&mut runner, your_token);
    mark_token(&mut runner, foe_token);

    // CR 613.4c: the token you control gains +1/+1 → 2/2.
    assert_eq!(
        effective_pt(&mut runner, your_token),
        (2, 2),
        "a creature token you control must get +1/+1"
    );

    // CR 111.1: a non-token you control is outside the token filter.
    assert_eq!(
        effective_pt(&mut runner, your_nontoken),
        (2, 2),
        "a non-token creature you control must be unaffected"
    );

    // CR 111.1: Phantom General itself is not a token — unaffected.
    assert_eq!(
        effective_pt(&mut runner, general),
        (2, 2),
        "Phantom General is not a token and must not buff itself"
    );

    // CR 109.5: "you control" excludes the opponent's token.
    assert_eq!(
        effective_pt(&mut runner, foe_token),
        (1, 1),
        "an opponent's token must be unaffected ('you control')"
    );
}

#[test]
fn phantom_general_buff_turns_off_when_source_leaves() {
    let mut scenario = GameScenario::new();
    scenario.at_phase(Phase::PreCombatMain);

    let general = scenario
        .add_creature_from_oracle(P0, "Phantom General", 2, 2, PHANTOM_GENERAL)
        .id();
    let your_token = scenario.add_creature(P0, "Soldier Token", 1, 1).id();

    let mut runner = scenario.build();
    mark_token(&mut runner, your_token);
    assert_eq!(
        effective_pt(&mut runner, your_token),
        (2, 2),
        "baseline: your token buffed to 2/2 while the source is present"
    );

    // Remove the anthem source from the battlefield (CR 611.3: the continuous
    // effect ends when its source leaves); the token reverts to base 1/1.
    {
        let state = runner.state_mut();
        state.battlefield.retain(|&id| id != general);
        state.objects.remove(&general);
    }
    assert_eq!(
        effective_pt(&mut runner, your_token),
        (1, 1),
        "your token must revert to base 1/1 once the anthem source is gone"
    );
}
