rule = "717.1"
section = 717
title = "Attraction Cards - CR 717.1"
status = "skeleton"
text = "Attraction is an artifact subtype seen only on nontraditional Magic cards. Each Attraction has an “Astrotorium” card back rather than a traditional Magic card back and has a column of circled numbers on the right side of its text box. Numbers in white text on a brightly colored background are said to be “lit up” on those cards. Note that multiple Attraction cards with the same English name may have different numbers lit up. You can see each Attraction card’s possible combinations of lights at Gatherer.Wizards.com."
