rule = "505.3"
section = 505
title = "Main Phase - CR 505.3"
status = "skeleton"
text = "First, but only if the players are playing an Archenemy game (see rule 904), the active player is the archenemy, and it’s the active player’s precombat main phase, the active player sets the top card of their scheme deck in motion (see rule 701.32). This turn-based action doesn’t use the stack."
