rule = "403.5"
section = 403
title = "Battlefield - CR 403.5"
status = "skeleton"
text = "Previously, the battlefield was called the “in-play zone.” Cards that were printed with text that contains the phrases “in play,” “from play,” “into play,” or the like are referring to the battlefield. Cards that were printed with that text have received errata in the Oracle card reference."
