import type { WasmGameAction, WasmPhase } from "../wasm/engine_wasm";

/**
 * Re-export WASM-generated action type as the canonical GameAction.
 * These types are auto-generated by tsify from the Rust enum definitions.
 */
export type GameAction = WasmGameAction;

/**
 * Game state returned by the engine. Mirrors the Rust GameState struct.
 * Typed here to match serde JSON output until tsify exports it directly.
 */
export interface GameState {
  turn_number: number;
  active_player: number;
  phase: WasmPhase;
  players: Player[];
  priority_player: number;
}

export interface Player {
  id: number;
  life: number;
  mana_pool: ManaPool;
}

export interface ManaPool {
  white: number;
  blue: number;
  black: number;
  red: number;
  green: number;
  colorless: number;
}

/**
 * Game events emitted by the engine. Placeholder until tsify exports them.
 * The Rust GameEvent enum uses tagged serialization (type + data).
 */
export interface GameEvent {
  type: string;
  data?: unknown;
}

/**
 * Error type for adapter operations. Wraps WASM/transport errors
 * with structured metadata for error handling in the UI layer.
 */
export class AdapterError extends Error {
  readonly code: string;
  readonly recoverable: boolean;

  constructor(code: string, message: string, recoverable: boolean) {
    super(message);
    this.name = "AdapterError";
    this.code = code;
    this.recoverable = recoverable;
  }
}

/** Error codes for AdapterError */
export const AdapterErrorCode = {
  NOT_INITIALIZED: "NOT_INITIALIZED",
  WASM_ERROR: "WASM_ERROR",
  INVALID_ACTION: "INVALID_ACTION",
} as const;

/**
 * Transport-agnostic interface for communicating with the game engine.
 * Phase 1: WasmAdapter (direct WASM calls)
 * Phase 7: TauriAdapter (IPC to native Rust process)
 */
export interface EngineAdapter {
  initialize(): Promise<void>;
  submitAction(action: GameAction): Promise<GameEvent[]>;
  getState(): Promise<GameState>;
  dispose(): void;
}
