import type { DeckEntry } from "../hooks/useDecks";

/**
 * Hand-curated bundled cEDH decks, keyed by stable id.
 *
 * Distinct from the MTGJSON-generated precon catalog (decks.json):
 * - decks.json is regenerated by oracle-gen from upstream MTGJSON data;
 *   hand edits would be overwritten.
 * - These entries are authored in TypeScript and surface through the same
 *   precon-source path in buildDeckCatalog, but with bracket: 5 baked in.
 *
 * Each entry MUST set type === "Commander Deck" so isCommanderPreconDeck
 * accepts it and the precon flow in deckCatalog.ts doesn't filter it out.
 *
 * IDs MUST use the `BundledCedh_` prefix so they cannot collide with
 * MTGJSON-derived deck ids (which use the `<DeckName>_<SetCode>` convention).
 */
export const BUNDLED_CEDH_DECKS: Readonly<Record<string, DeckEntry>> = {
  /**
   * Demo deck — Heliod, Sun-Crowned + Walking Ballista combo.
   *
   * Mono-white Commander build. All 99 mainboard slots are filled and the
   * deck is legal per CR 903.4 (color identity) and CR 903.5a (100-card
   * minimum including the commander). The curated portion is demo-quality
   * (not a real tournament list) and the remainder is padded with Plains so
   * the picker always has a well-formed 100-card deck to hand to the engine.
   *
   * Cards with off-color identity (blue/black) were removed in a correctness
   * pass: Thassa's Oracle, Demonic Consultation, Mystical Tutor, Demonic
   * Tutor, Vampiric Tutor, Brainstorm, Ponder, Preordain, Counterspell,
   * Force of Will, Swan Song, Mana Drain, Island, Swamp.
   */
  BundledCedh_HeliodBallista_Demo: {
    code: "BCDH",
    name: "cEDH Demo - Heliod Combo",
    type: "Commander Deck",
    releaseDate: undefined,
    // Placeholder: a real coverage % is computed by the engine when the
    // deck is evaluated through `evaluateDeckCompatibility`. The catalog
    // surfaces this value only for UI display; it does not gate inclusion.
    coveragePct: 0,
    commander: [{ name: "Heliod, Sun-Crowned", count: 1 }],
    mainBoard: [
      // Combo piece
      { name: "Walking Ballista", count: 1 },

      // Fast mana / ramp (all colorless or mono-white)
      { name: "Sol Ring", count: 1 },
      { name: "Mana Crypt", count: 1 },
      { name: "Mox Diamond", count: 1 },
      { name: "Lotus Petal", count: 1 },
      { name: "Arcane Signet", count: 1 },
      { name: "Mind Stone", count: 1 },

      // Removal (mono-white)
      { name: "Swords to Plowshares", count: 1 },
      { name: "Path to Exile", count: 1 },
      { name: "Generous Gift", count: 1 },

      // Tutors (mono-white only)
      { name: "Enlightened Tutor", count: 1 },

      // Utility
      { name: "Sensei's Divining Top", count: 1 },

      // Lands (colorless color identity — legal in mono-white per CR 903.4)
      { name: "Command Tower", count: 1 },
      { name: "Mana Confluence", count: 1 },
      { name: "City of Brass", count: 1 },
      { name: "Reflecting Pool", count: 1 },
      { name: "Exotic Orchard", count: 1 },

      // Plains — padded to reach exactly 99 mainboard copies (CR 903.5a)
      // Curated slots: 17 (above). Padding: 99 − 17 = 82. Total Plains: 82.
      { name: "Plains", count: 82 },
    ],
  },
};
