#!/usr/bin/env python3
"""Generate the engine's dated Commander AI deck manifest from tracked sources."""

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
# The live feed at client/public/feeds/mtggoldfish-commander.json is refreshed
# upstream almost daily, so the manifest reads a vendored copy of the exact
# 2026-09-08 feed it was generated from. `--check` stays reproducible across
# feed refreshes; re-dating the manifest means replacing this snapshot.
FEED_PATH = ROOT / "crates/engine/data/ai_commander_decks.feed-2026-09-08.json"
CEDH_PATH = ROOT / "client/src/data/cedhDecks.ts"
OUTPUT_PATH = ROOT / "crates/engine/data/ai_commander_decks.json"
VERSION = "2026-09-27"
SOURCE = (
    "generated by scripts/gen-ai-commander-decks.py from "
    "client/public/feeds/mtggoldfish-commander.json (updated 2026-09-08) "
    "and client/src/data/cedhDecks.ts"
)
CEDH_ID_RE = re.compile(r"^  (BundledCedh_[A-Za-z0-9_]+): \{$", re.MULTILINE)
CARD_RE = re.compile(r'\{ name: "((?:[^"\\]|\\.)+)", count: ([0-9]+) \}')


def decode_ts_string(value: str) -> str:
    return json.loads(f'"{value}"')


def slug(value: str) -> str:
    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", ascii_value.lower()).strip("-")


def expand_cards(section: str, *, label: str) -> list[str]:
    matches = CARD_RE.findall(section)
    if section.count("{ name:") != len(matches):
        raise ValueError(f"{label}: unsupported card entry syntax")
    cards = []
    for raw_name, raw_count in matches:
        count = int(raw_count)
        if count < 1:
            raise ValueError(f"{label}: card count must be positive")
        cards.extend([decode_ts_string(raw_name)] * count)
    return cards


def cedh_blocks(raw: str) -> list[tuple[str, str]]:
    starts = list(CEDH_ID_RE.finditer(raw))
    if len(starts) != 3:
        raise ValueError(f"expected exactly 3 BundledCedh entries, found {len(starts)}")
    blocks = []
    for index, match in enumerate(starts):
        end = starts[index + 1].start() if index + 1 < len(starts) else raw.index("\n};", match.end())
        blocks.append((match.group(1), raw[match.start():end]))
    return blocks


def section(block: str, field: str, next_field: str | None) -> str:
    if next_field is None:
        pattern = rf"\n    {field}:\s*\[(.*?)\n    \],"
    else:
        pattern = rf"\n    {field}:\s*\[(.*?)\],\s*\n    {next_field}:\s*\["
    match = re.search(pattern, block, re.DOTALL)
    if match is None:
        raise ValueError(f"could not parse {field} section")
    return match.group(1)


def load_feed_decks() -> tuple[list[dict], str]:
    feed = json.loads(FEED_PATH.read_text(encoding="utf-8"))
    decks = feed.get("decks")
    if not isinstance(decks, list) or len(decks) != 10:
        raise ValueError(f"expected exactly 10 feed decks, found {len(decks) if isinstance(decks, list) else 'no deck list'}")
    updated = feed.get("updated", "").split("T", 1)[0]
    if updated != "2026-09-08":
        raise ValueError(f"unexpected feed date: {feed.get('updated')!r}")

    generated = []
    for deck in decks:
        commander = deck["name"]
        main_deck = []
        for card in deck["main"]:
            if card["name"].casefold() != commander.casefold():
                main_deck.extend([card["name"]] * card["count"])
        generated.append(
            {
                "id": f"feed:{slug(commander)}",
                "name": commander,
                "commander": [commander],
                "main_deck": main_deck,
                "declared": None,
                "source": "mtggoldfish-commander feed",
                "source_date": updated,
            }
        )
    return generated, updated


def load_cedh_decks() -> list[dict]:
    raw = CEDH_PATH.read_text(encoding="utf-8")
    generated = []
    for deck_id, block in cedh_blocks(raw):
        name_match = re.search(r'^    name: "((?:[^"\\]|\\.)+)",$', block, re.MULTILINE)
        if name_match is None:
            raise ValueError(f"{deck_id}: display name is missing")
        commanders = expand_cards(section(block, "commander", "mainBoard"), label=f"{deck_id}.commander")
        if not commanders:
            raise ValueError(f"{deck_id}: commander list is empty")
        main_deck = expand_cards(section(block, "mainBoard", None), label=f"{deck_id}.mainBoard")
        date_match = re.search(r'^    releaseDate: "([0-9]{4}-[0-9]{2}-[0-9]{2})",$', block, re.MULTILINE)
        generated.append(
            {
                "id": deck_id,
                "name": decode_ts_string(name_match.group(1)),
                "commander": commanders,
                "main_deck": main_deck,
                "declared": "cedh",
                "source": "phase bundled cEDH demo",
                "source_date": date_match.group(1) if date_match else VERSION,
            }
        )
    return generated


def generate() -> bytes:
    feed_decks, _ = load_feed_decks()
    manifest = {
        "version": VERSION,
        "source": SOURCE,
        "decks": feed_decks + load_cedh_decks(),
    }
    return (json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed output differs")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        try:
            current = OUTPUT_PATH.read_bytes()
        except FileNotFoundError:
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        if current != generated:
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is not up to date", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.write_bytes(generated)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
        print(f"generation failed: {error}", file=sys.stderr)
        raise SystemExit(1) from error
