# Comprehensive Rules Section 725: The Initiative

[_meta]
section = 725
title = "The Initiative"

[cr_725_1]
rule = "725.1"
text = "The initiative is a designation a player can have. There is no initiative in a game until an effect instructs a player to take the initiative. A player who currently has the initiative designation is said to have the initiative."
status = "missing"
impl_files = []
test_files = []
notes = "The Initiative (Baldur's Gate Commander) not implemented."

[cr_725_2]
rule = "725.2"
text = "There are three inherent triggered abilities associated with having the initiative. These triggered abilities have no source and are controlled by the player who had the initiative at the time the abilities triggered. This is an exception to rule 113.8. The full text of these abilities are \"At the beginning of the upkeep of the player who has the initiative, that player ventures into Undercity,\" \"Whenever one or more creatures a player controls deal combat damage to the player who has the initiative, the controller of those creatures takes the initiative,\" and \"Whenever a player takes the initiative, that player ventures into Undercity.\" See rule 701.49, \"Venture into the Dungeon.\""
status = "missing"
impl_files = []
test_files = []
notes = "The Initiative not implemented."

[cr_725_3]
rule = "725.3"
text = "Only one player can have the initiative at a time. As a player takes the initiative, the player who currently has the initiative ceases to have it."
status = "missing"
impl_files = []
test_files = []
notes = "The Initiative not implemented."

[cr_725_4]
rule = "725.4"
text = "If the player who has the initiative leaves the game, the active player takes the initiative at the same time that player leaves the game. If the active player is leaving the game or if there is no active player, the next player in turn order takes the initiative."
status = "missing"
impl_files = []
test_files = []
notes = "The Initiative not implemented."

[cr_725_5]
rule = "725.5"
text = "If the player who currently has the initiative is instructed to take the initiative, this causes the last triggered ability in 725.2 to trigger but does not create a second initiative designation."
status = "missing"
impl_files = []
test_files = []
notes = "The Initiative not implemented."
