rule = "100.4"
section = 100
title = "General - CR 100.4"
status = "skeleton"
text = "Each player may also have a sideboard, which is a group of additional cards the player may use to modify their deck between games of a match. Sideboard rules and restrictions for some formats are modified by the Magic: The Gathering Tournament Rules (found at WPN.Wizards.com/en/rules-documents)."
