rule = "100.2b"
section = 100
title = "General - CR 100.2b"
status = "skeleton"
text = "In limited play (a way of playing in which each player gets the same quantity of unopened Magic product such as booster packs and creates their own deck using only this product and basic land cards), each deck has a minimum deck size of 40 cards. A limited deck may contain as many duplicates of a card as are included with the product."
